# https://help.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
# Maintain dependencies for maven
  - package-ecosystem: "maven"
    directory: "/"
    schedule:
      interval: "weekly"
    ignore:
      # The 2.0.0 release is the first release under the jakarta.activation.* namespace
      - dependency-name: "jakarta.activation:jakarta.activation-api"
        versions: [">=2.0.0"]
      # The 3.0.0 release is the first release under the jakarta.xml.bind.* namespace
      - dependency-name: "jakarta.xml.bind:jakarta.xml.bind-api"
        versions: [">=3.0.0"]
      # Provided by the web container, so aligned with Jetty
      - dependency-name: "javax.servlet:javax.servlet-api"
      # Newer versions require code changes
      # N/A
# Maintain dependencies for GitHub actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"