---
name: Sync project branch
on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:
jobs:
  sync-project-branch:
    runs-on: ubuntu-latest
    if: github.repository_owner == 'jenkinsci'
    steps:
      - uses: actions/checkout@v4
        with:
          ref: gsoc-2023-project
      - run: |
          git fetch --unshallow origin || git fetch origin
          git config user.email "sync-project-branch@jenkins.io"
          git config user.name "Sync project branch action"
          git merge --no-edit origin/master
      - uses: peter-evans/create-pull-request@v5
        with:
          title: Merge remote-tracking branch `origin/master` into `gsoc-2023-project`
          branch: sync-project-branch
          delete-branch: true
